my_script:
  image: aaron2397/pack_some_script:latest
  container_name: my_script
  restart: always
  tty: true
  volumes:
    - ./logs:/logs
    #- ./my_crontab_list.sh:/pss/my_crontab_list.sh #挂载自定义任务文件
  environment:
    #20201219增加自定义任务配置
    #使用自定义定任务之后，上面volumes挂载之后这里配置对应的文件名
    #- CUSTOM_LIST_FILE=my_crontab_list.sh #自定任务文件名
    #- CUSTOM_LIST_MERGE_TYPE=append #默认值append自定文件的使用方式append追加默认之后，overwrite覆盖默认任务
    # 注意环境变量填写值的时候一律不需要引号（""或者''）下面这些只是事例，根据自己的需求增加删除
    # 公用通知相关环境变量
    # server酱服务
    - PUSH_KEY=
    # bark服务
    - BARK_PUSH=
    - BARK_SOUND=
    # telegram机器人通知
    - TG_BOT_TOKEN=
    - TG_USER_ID=
    # 钉钉通知bot token
    - DD_BOT_TOKEN=
    - DD_BOT_SECRET=
    # 喜马拉雅极速版相关，原作者使用\n换行传入多个cookie，脚本里面没有处理环境变量转译，改为用|来连接多个cookies
    - XMLY_ACCUMULATE_TIME=1 #设置为1开启刷时长，0为关闭刷时长
    - AUTO_TAKE_OUT=True #自动提现开关，设置True为开启自动提现，False为关闭自动提现，默认为False
    - XMLY_NOTIFY_TIME=23 #喜马拉雅通知时间，要填写2位，例如8点就写08，默认为19
    - XMLY_SPEED_COOKIE=
    # 企鹅读书相关
    # 多账号 cookies连接符号，不配置默认为|，自己有能力调整排错的可以尝试自定义,因为汽车之家body里面呢包含| ,使用汽车之家建议改为|&|，否则会汽车之家任务无法执行
    - COOKIES_SPLIT=|&|
    #- QQREAD_CASH=1 #企鹅读书自动提现金额设置，可选项为:1,2,10,30,50,100
    # 上面COOKIES_SPLIT配置的什么下面用什么连接多个qqreadbodyVal
    #- QQREAD_BODY=
    # 上面COOKIES_SPLIT配置的什么下面用什么连接多个qqreadtimeurlVal
    #- QQREAD_TIMEURL=
    # 上面COOKIES_SPLIT配置的什么下面用什么连接多个qqreadtimeheaderVal
    #- QQREAD_TIMEHD=
    # 汽车之家需要抓包配置的环境变量
    - QCZJ_CASH=0.5 #设置自动提现金额,可设置(0.5,2,5,10,20)
    - QCZJ_CASHTYPE=1 #设置自动提现方式，1为提现到汽车之家钱包，3为提现到微信，默认为3，提现到微信时需先绑定
    - QCZJ_GetUserInfoHEADER=
    - QCZJ_taskBODY=
    - QCZJ_activityBODY=
    - QCZJ_addCoinBODY=
    - QCZJ_addCoin2BODY=
    # 笑谱相关环境变量
    - XP_CASH=15 #设置自动提现金额,可设置(1,15,30,100)
    - XP_live=1 #设置笑谱执行任务,设置为0只执行视频任务,设置为1执行视频和直播任务,设置为2只执行直播任务
    - XP_refreshTOKEN=
    # 返利网相关环境变量
    - FL_CASH=0.3
    - FL_DHCASH=5
    - FL_flwURL=
    - FL_flwHEADER=
    - FL_flwspBODY=
    - FL_flwqwBODY=
    # 多看点相关变量
    - DKD_duokandianCASH=50 #设置自动提现金额,可设置(1,3,5,15,50)
    - DKD_duokandianBODY=
    - DKD_duokandianvideoBODY=
    # 芝嫲视频相关变量
    - ZM_zhimabody=
    # 步步宝相关环境变量
    - BBB_COOKIE=
    # 火山小视频极速版(多账号用#分割)
    - HOTSOONSIGNHEADER=
    - HOTSOONADHEADER=
    - HOTSOONADKEY=
    - HOTSOONREADHEADER=
    # 小米运动刷步数
    - XMYD_USER=
    - XMYD_PASSWD=
    - XMYD_STEP=20000-25000